config/routes.rb
InPaymentSchedulex::Engine.routes.draw do
  resources :receiving_schedules do
    collection do
      get :search
      get :search_results
    end
  end

  root :to => 'receiving_schedules#index'

end

app/models/in_payment_schedulex/receiving_schedule.rb
module InPaymentSchedulex
  class ReceivingSchedule < ActiveRecord::Base
    attr_accessor :last_update_by_name, :payment_type, :cancelled_noupdate, :contract_id_noupdate, :paid_out_noupdate
                                   
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :contract, :class_name => InPaymentSchedulex.contract_class.to_s
    belongs_to :payment_type, :class_name => 'Commonx::MiscDefinition'

    validates :amount, :presence => true,
                       :numericality => {:greater_than_or_equal_to => 0}                            
    validates :pay_date, :presence => true
    validates :contract_id, :presence => true, :numericality => {:greater_than => 0}
    validates :paid_percentage, :numericality => {:greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}, :if => 'paid_percentage.present?'
    validates :payment_type_id, :numericality => {:greater_than => 0}, :if => 'payment_type_id.present?'
    validate :dynamic_validate 
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'in_payment_schedulex')
      eval(wf) if wf.present?
    end        
  end
end

app/controllers/in_payment_schedulex/application_controller.rb
module InPaymentSchedulex
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    
    #before_action :require_signin
    before_action :max_pagination
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
   
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
    
    #engine's
    def return_customers_by_access_right     
      access_rights, model_ar_r, has_record_access = access_right_finder('index', InPaymentSchedulex.customer_class.to_s.underscore.pluralize, session[:user_role_ids], nil,nil,nil,nil, session[:user_id])
      return [] if access_rights.blank?
      return model_ar_r #instance_eval(access_rights.sql_code) #.present?
    end
  end
end

app/controllers/in_payment_schedulex/receiving_schedules_controller.rb
require_dependency "in_payment_schedulex/application_controller"

module InPaymentSchedulex
  class ReceivingSchedulesController < ApplicationController
    before_action :require_employee
    before_action :load_parent_record

    def index
      @title = t('Receiving Schedules')
      @receiving_schedules = params[:in_payment_schedulex_receiving_schedules][:model_ar_r]
      @receiving_schedules = @receiving_schedules.where(:contract_id => @contract.id) if @contract      
      @receiving_schedules = @receiving_schedules.page(params[:page]).per_page(@max_pagination)     
      @erb_code = find_config_const('receiving_schedule_index_view', 'in_payment_schedulex')
    end


    def new
      @title = t('New Receiving Schedule')
      @receiving_schedule = InPaymentSchedulex::ReceivingSchedule.new
      @erb_code = find_config_const('receiving_schedule_new_view', 'in_payment_schedulex')
    end


    def create
      @receiving_schedule = InPaymentSchedulex::ReceivingSchedule.new(new_params)
      @receiving_schedule.last_updated_by_id = session[:user_id]
      if @receiving_schedule.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        #for render new when data error
        @contract = InPaymentSchedulex.contract_class.find_by_id(params[:receiving_schedule][:contract_id]) if params[:receiving_schedule].present? && params[:receiving_schedule][:contract_id].present? 
        @erb_code = find_config_const('receiving_schedule_new_view', 'in_payment_schedulex')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end

    def edit
      @title = t('Edit Receiving Schedule')
      @receiving_schedule = InPaymentSchedulex::ReceivingSchedule.find_by_id(params[:id])
      @erb_code = find_config_const('receiving_schedule_edit_view', 'in_payment_schedulex')
    end

    def update
      @receiving_schedule = InPaymentSchedulex::ReceivingSchedule.find_by_id(params[:id])
      @receiving_schedule.last_updated_by_id = session[:user_id]
      if @receiving_schedule.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('receiving_schedule_edit_view', 'in_payment_schedulex')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end

    def show
      @title = t('Receiving Schedule Info')
      @receiving_schedule = InPaymentSchedulex::ReceivingSchedule.find_by_id(params[:id])
      @erb_code = find_config_const('receiving_schedule_show_view', 'in_payment_schedulex')
    end

    protected
    
    def load_parent_record
      @contract = InPaymentSchedulex.contract_class.find_by_id(params[:contract_id]) if params[:contract_id].present? 
      @contract = InPaymentSchedulex.contract_class.find_by_id(InPaymentSchedulex::ReceivingSchedule.find_by_id(params[:id]).contract_id) if params[:id].present? 
    end
    
    private
    
    def new_params
      params.require(:receiving_schedule).permit(:amount, :brief_note, :contract_id, :paid_percentage, :pay_date, :payment_type_id, :paid_out)
    end
    
    def edit_params
      params.require(:receiving_schedule).permit(:amount, :brief_note, :paid_percentage, :pay_date, :payment_type_id, :pay_out_date, :paid_out)
    end
  end
end

app/helpers/in_payment_schedulex/application_helper.rb
module InPaymentSchedulex
  module ApplicationHelper
  end
end

app/helpers/in_payment_schedulex/receiving_schedules_helper.rb
module InPaymentSchedulex
  module ReceivingSchedulesHelper
  end
end

app/views/in_payment_schedulex/receiving_schedules/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
  <h4><%= t(@title) %></h4>
<%= simple_form_for(@receiving_schedule) do |f| %>
    <%= f.input :contract_id_noupdate, :label => t('Contract#'), :readonly => true, :input_html => {:value => @contract.id} %>
    <%= f.input :pay_date, :label => t('Pay Date'), :as => :string %>
    <%= f.input :amount, :label => t('Payment Amount($)') %>
    <%= f.input :paid_percentage, :label => t('Paid Percentage(%)'), :collection => Array(0..100) %>
    <%= f.input :pay_out_date, :label => t('Pay Out Date'), :as => :string %>
    <%= f.input :brief_note,:label => t('Brief Note') %>
    
    <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
    <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>
<% end %>

<% end %>

app/views/in_payment_schedulex/receiving_schedules/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div class="pagination"><%= will_paginate models %></div>
<h4><%= t(@title) %></h4>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th><%= t('Contract#') %></th>
    <th><%= t('Pay Date') %></th>
    <th><%= t('Amount') %></th>
    <th><%= t('Brief Note') %></th>
    <th><%= t('Last Updated By') %></th>
    <th></th>
  </tr>
<% models.each do |r| %>
  <tr>
    
    <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(receiving_schedule_path(r))}" %></td>
  	<% if has_action_right?('show', InPaymentSchedulex.contract_resource, InPaymentSchedulex.contract_class.find_by_id(r.contract_id) ) %>
  	  <td><%= link_to r.contract_id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(InPaymentSchedulex.show_contract_path))}"  %></td>
  	<% else %>
  	  <td><%= prt(r, 'contract_id') %></td>
  	<% end %>  
    <td><%= prt(r, :pay_date).strftime('%Y/%m/%d') %></td>
    <td><%= number_with_precision(prt(r, :amount), :precision => 2) %></td>
    <td><%= prt(r, :brief_note) %></td>
    <td><%= prt(r, 'last_updated_by.name') if r.last_updated_by_id.present? %></td>

    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(edit_receiving_schedule_path(r))}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
   </tr>
<% end %>
</table>
<table class="table table-striped">
  <tr>
    <th>
    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
    	<%= link_to t('New Receiving Schedule'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape(new_receiving_schedule_path(:contract_id => @contract.id, :parent_record_id => @contract.id, :parent_resource => InPaymentSchedulex.contract_resource))}", :class => BUTTONS_CLS['action'] if @contract && has_action_right?('create', params[:controller], InPaymentSchedulex.contract_class.find_by_id(@contract.id)) %>
    	<%= link_to t('Search'), SUBURI + "/authentify/view_handler?index=1&url=#{search_receiving_schedules_path}", :class => BUTTONS_CLS['action'] %>
    </th>
  </tr>
</table>

<% end %>

app/views/in_payment_schedulex/receiving_schedules/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
  <h4><%= t(@title) %></h4>
<%= simple_form_for(@receiving_schedule) do |f| %>
    <%= f.input :contract_id, :label => t('Contract#'), :readonly => true, :input_html => {:value => @contract.id} %>
    <%= f.input :pay_date, :label => t('Pay Date'), :as => :string %>
    <%= f.input :amount, :label => t('Payment Amount($)') %>
    <%= f.input :brief_note,:label => t('Brief Note') %>

    <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
    <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>
<% end %>

<% end %>

app/views/in_payment_schedulex/receiving_schedules/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/in_payment_schedulex/receiving_schedules/edit.html.erb
 
<%= render 'form' %>
 

  
 

app/views/in_payment_schedulex/receiving_schedules/index.html.erb
  <%= render partial: 'form_list', locals: {models: @receiving_schedules} %>

app/views/in_payment_schedulex/receiving_schedules/new.html.erb
  <%= render 'form_new' %>

app/views/in_payment_schedulex/receiving_schedules/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>

<h4><%= t(@title) %></h4>

<p>
  <b><%= t('Contract#') %></b>
  <%= @contract.id %>
</p>
<p>
  <b><%= t('Amount') %></b>
  <%= number_with_precision(@receiving_schedule.amount, :precision => 2) %>
</p>
<p>
  <b><%= t('Pay Date') %></b>
  <%= @receiving_schedule.pay_date %>
</p>
<p>
  <b><%= t('Paid Percentage%') %></b>
  <%= @receiving_schedule.paid_percentage %>%
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @receiving_schedule.last_updated_by.name if @receiving_schedule.last_updated_by_id.present? %>
</p>
<p>
    <b><%= t('Brief Note') %></b>
    <%= @receiving_schedule.brief_note %>
</p>
<p>
  <b><%= t('Log') %></b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @receiving_schedule.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.last_updated_by.name %>,&nbsp; <%= t.log %></li>
  <% end %>
</p>
  
  <table class="table table-striped">
	  <tr>
	    <th>
			<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    	    <%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @receiving_schedule.id, :resource_name => params[:controller], :subaction => 'pay_receiving_schedule',
    	     :format => :js), :remote => true, :id => 'new_log_link' , :class => BUTTONS_CLS['action'] if has_action_right?('create_pay_receiving_schedule', 'commonx/logs') %>
       </th>
  </tr>
</table>


<% end %>

app/views/in_payment_schedulex/receiving_schedules/update.html.erb
<h4>Projects#update</h4>
<p>Find me in app/views/projects/update.html.erb</p>